.PHONY: fonts css sass generateTtf generateWoff generateWoff2 generateCSS generateSASS help
.DEFAULT_GOAL := help

# Dependencies
FONTFORGE := $(shell which fontforge)
WOFF2     := $(shell which woff2_compress)

# Vars
FONT_NAME := $(notdir $(FONT_PATH))
FONT_EXT  := $(suffix $(FONT_NAME))
OUTPUT 		?= $(shell dirname $(FONT_PATH))/

# Functions
NEW_FILE_NAME = $(subst $(FONT_EXT),$(1),$(call FONT_NAME))
CSS_FILE      = $(subst $(FONT_EXT),.css,$(call FONT_NAME))
SASS_FILE     = $(subst $(FONT_EXT),.sass,$(call FONT_NAME))

fonts: generateTtf generateWoff generateWoff2 ## Generate ttf, woff and woff2 from otf file

css: fonts generateCSS ## Generate ttf, woff, woff2 and CSS file including font-face declarations
	
sass: fonts generateSASS ## Same as make simple with SASS file including font-face declarations

generateTtf:
	@$(FONTFORGE) -lang=ff -c 'Open($$1);Print($$fontname);' '$(FONT_PATH)' 2> /dev/null
	@$(FONTFORGE) -lang=ff -c 'Open($$1);Print($$weight);' '$(FONT_PATH)' 2> /dev/null
	@$(FONTFORGE) -lang=ff -c 'Open($$1);Print($$italicangle);' '$(FONT_PATH)' 2> /dev/null
	@$(FONTFORGE) -lang=ff -c 'Open($$1);SetFontNames($$3,$$3,$$3);Generate($$2, "", 8);' '$(FONT_PATH)' '$(OUTPUT)$(call NEW_FILE_NAME,.ttf)' 'false' 2> /dev/null

generateWoff: 
	@$(FONTFORGE) -lang=ff -c 'Open($$1);Generate($$2, "", 8);' '$(FONT_PATH)' '$(OUTPUT)$(call NEW_FILE_NAME,.woff)' 2> /dev/null

generateWoff2: 
	@$(WOFF2) "$(OUTPUT)$(call NEW_FILE_NAME,.ttf)"

generateCSS:
	@echo "/* Generated by Fontface Maker - https://github.com/Awea/fontfacemaker */" > $(OUTPUT)$(CSS_FILE)
	@echo @font-face { >> $(OUTPUT)$(CSS_FILE)
	@echo	"  font-family: '$(call NEW_FILE_NAME)';" >> $(OUTPUT)$(CSS_FILE)
	@echo	"  src: url('$(call NEW_FILE_NAME,.woff2)') format('woff2')," >> $(OUTPUT)$(CSS_FILE)
	@echo	"       url('$(call NEW_FILE_NAME,.woff)') format('woff')," >> $(OUTPUT)$(CSS_FILE)
	@echo	"       url('$(call NEW_FILE_NAME,.ttf)') format('truetype');" >> $(OUTPUT)$(CSS_FILE)
	@echo } >> $(OUTPUT)$(CSS_FILE)

generateSASS:
	@echo "// Generated by Fontface Maker - https://github.com/Awea/fontfacemaker" > $(OUTPUT)$(SASS_FILE)
	@echo @font-face >> $(OUTPUT)$(SASS_FILE)
	@echo	"  font-family: '$(call NEW_FILE_NAME)';" >> $(OUTPUT)$(SASS_FILE)
	@echo	"  src: url('$(call NEW_FILE_NAME,.woff2)') format('woff2'), url('$(call NEW_FILE_NAME,.woff)') format('woff'), url('$(call NEW_FILE_NAME,.ttf)') format('truetype')" >> $(OUTPUT)$(SASS_FILE)

help: ## This help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
